# Generated by Django 4.1.13 on 2025-09-29 10:49

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/default.png', upload_to=User.models.image_path),
        ),
    ]
