# Generated by Django 4.1.13 on 2025-10-12 06:13

import User.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_icon', models.ImageField(blank=True, null=True, upload_to='class_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_title', models.CharField(max_length=150)),
                ('problem_description', models.TextField()),
                ('problem_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz')], max_length=20)),
                ('total_score', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.class')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.png', upload_to=User.models.image_path),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.problem')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('testcase_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='User.user'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'unique_together': {('class_id', 'student_id')},
            },
        ),
    ]
