# Generated by Django 5.2.7 on 2025-10-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_class_problem_alter_user_user_image_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='upload_icon',
            field=models.ImageField(blank=True, default='class_icons/defaultClassIcon.png', null=True, upload_to='class_icons/'),
        ),
    ]
